SELECT COLUMN_NAME,DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'COVID_DEATH'

EXEC sp_columns 'COVID_DEATH'


SELECT *
FROM PORTFOLIO_PROJECT..COVID_DEATH
WHERE CONTINENT IS NOT NULL
ORDER BY 3,4

--SELECT *
--FROM PORTFOLIO_PROJECT..COVID_VACCINATION
--ORDER BY 3,4

-- SELECT DATA THAT WE ARE GOING TO BE USING

SELECT location,date,total_cases,new_cases,total_deaths,population
FROM PORTFOLIO_PROJECT..COVID_DEATH
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

-- LOOKING AT TOTAL CASES VS TOTAL DEATHS

ALTER TABLE COVID_DEATH
ALTER COLUMN total_cases FLOAT

ALTER TABLE COVID_DEATH
ALTER COLUMN total_deaths FLOAT

--SHOWS LIKLIHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY

SELECT location,date,total_cases,total_deaths,(total_deaths / NULLIF(total_cases,0)) * 100 AS DEATH_PERCENTAGE
FROM PORTFOLIO_PROJECT..COVID_DEATH
WHERE CONTINENT IS NOT NULL
ORDER BY location,date


SELECT location, YEAR(date)AS YEAR,SUM(total_cases) AS TOTAL_CASES,SUM(total_deaths) AS TOTAL_DEATH
FROM PORTFOLIO_PROJECT..COVID_DEATH
WHERE CONTINENT IS NOT NULL
GROUP BY location,YEAR(date)
ORDER BY location, YEAR(date)

SELECT 
    location,
    YEAR(date) AS YEAR,
    SUM(total_cases) AS TOTAL_CASES,
    SUM(total_deaths) AS TOTAL_DEATH,
    (SUM(total_deaths) * 100.0) / NULLIF(SUM(total_cases), 0) AS DEATH_PERCENTAGE
FROM PORTFOLIO_PROJECT..COVID_DEATH
WHERE CONTINENT IS NOT NULL
GROUP BY location, YEAR(date)
ORDER BY location, YEAR(date); 


-- LOOKING AT TOTAL CASES VS POPULATION
-- SHOWES WHAT PERCENTAGE OF POPULATIONS GOT COVID

SELECT location,date,population,total_cases,(total_cases/NULLIF(population,0))*100 AS PERCENT_POPULATIN_INFECTED
FROM PORTFOLIO_PROJECT..COVID_DEATH
ORDER BY 1,2

--LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARE TO THE POPULATION


SELECT location,population,MAX(total_cases)AS HIGHEST_INFECTION_COUNT ,MAX((total_cases/NULLIF(population,0)))*100 AS PERCENT_POPULATIN_INFECTED
FROM PORTFOLIO_PROJECT..COVID_DEATH
GROUP BY location,population
ORDER BY PERCENT_POPULATIN_INFECTED DESC

-- SHOWING COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION

SELECT location, MAX(total_deaths) AS TOTAL_DEATH_COUNT
FROM PORTFOLIO_PROJECT..COVID_DEATH
WHERE CONTINENT IS NOT NULL
GROUP BY location
ORDER BY TOTAL_DEATH_COUNT DESC


--LET'S BREAK THINGS DOWN BY CONTINENT


-- SHOWING CONTINENTS WITH HIGHEST DEATH COUNT PER POPULATION

SELECT continent, MAX(total_deaths) AS TOTAL_DEATH_COUNT
FROM PORTFOLIO_PROJECT..COVID_DEATH
WHERE CONTINENT IS NOT NULL
GROUP BY continent
ORDER BY TOTAL_DEATH_COUNT DESC

-- GLOBAL NUMBERS

SELECT SUM(new_cases) AS TOTAL_CASES, SUM(CAST(new_deaths AS INT)) AS TOTAL_DEATHS,
		SUM(CAST(new_deaths AS INT)) / SUM(new_cases) *100 AS DEATH_PERCENTAGES
FROM PORTFOLIO_PROJECT..COVID_DEATH
WHERE continent IS NOT NULL
ORDER BY 1,2

--LOOKING TOTAL POPULATION VS VACCINATION

-- USE CTE

WITH POPvsVAC (continent,location,date,population,new_vaccinations,ROLLING_PEOPLE_VACCINATED)
AS
(
SELECT
    DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations,  
    SUM(CAST(VAC.new_vaccinations AS BIGINT)) OVER (PARTITION BY DEA.location ORDER BY DEA.location, DEA.date) 
	AS ROLLING_PEOPLE_VACCINATED
	--(ROLLING_PEOPLE_VACCINATED/population)*100
FROM
    PORTFOLIO_PROJECT..COVID_DEATH DEA
JOIN
    PORTFOLIO_PROJECT..COVID_VACCINATION VAC
ON
    DEA.location = VAC.location
    AND DEA.date = VAC.date
WHERE
    DEA.continent IS NOT NULL
--ORDER BY
--    2, 3;
)
SELECT *, (ROLLING_PEOPLE_VACCINATED/population)*100
FROM POPvsVAC


--TEMP TABLE 

DROP TABLE IF EXISTS #PERCENT_POP_VAC
CREATE TABLE #PERCENT_POP_VAC
(
	continent NVARCHAR(255),
	location NVARCHAR(255),
	date DATETIME,
	population NUMERIC,
	new_vaccinations NUMERIC,
	ROLLING_PEOPLE_VACCINATED NUMERIC
	)
INSERT INTO #PERCENT_POP_VAC
SELECT
    DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations,  
    SUM(CAST(VAC.new_vaccinations AS BIGINT)) OVER (PARTITION BY DEA.location ORDER BY DEA.location, DEA.date) 
	AS ROLLING_PEOPLE_VACCINATED
	--(ROLLING_PEOPLE_VACCINATED/population)*100
FROM
    PORTFOLIO_PROJECT..COVID_DEATH DEA
JOIN
    PORTFOLIO_PROJECT..COVID_VACCINATION VAC
ON
    DEA.location = VAC.location
    AND DEA.date = VAC.date
WHERE
    DEA.continent IS NOT NULL
--ORDER BY
--    2, 3;

SELECT *, (ROLLING_PEOPLE_VACCINATED/population)*100
FROM #PERCENT_POP_VAC

--===================   CREATING VIIEW TO STORE DATA FOR LATER VISUALISATIONS  ==========

CREATE VIEW PERCENT_POP_VAC AS
SELECT
    DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations,  
    SUM(CAST(VAC.new_vaccinations AS BIGINT)) OVER (PARTITION BY DEA.location ORDER BY DEA.location, DEA.date) 
	AS ROLLING_PEOPLE_VACCINATED
	--(ROLLING_PEOPLE_VACCINATED/population)*100
FROM
    PORTFOLIO_PROJECT..COVID_DEATH DEA
JOIN
    PORTFOLIO_PROJECT..COVID_VACCINATION VAC
ON
    DEA.location = VAC.location
    AND DEA.date = VAC.date
WHERE
    DEA.continent IS NOT NULL
--ORDER BY
--    2, 3;

SELECT * 
FROM PERCENT_POP_VAC